### ISSUE TITLE
Problems with output files

### ISSUE THREAD

**Issue by daniDevKr** [rictec/yaris_xl_device#1]
I used  "yaris_xl_device" with lineageOS 12 source code.
The project is build sucefully.
When i install the output installing package my device not working.
how can I solve this problem ?

**Comment by rictec** [comment]
as far as i remember  that tree i think its for version 4.1 (jelly beam) of android probably need changes to work on that version

**Comment by jhonToni** [comment]
What changes should I make to the code?

**Comment by daniDevKr** [comment]
What are the steps to download and build **CyanogenMod** for **alcatel onetouch pop c7**?   👍
